<a href="https://colab.research.google.com/github/noturnon2/myshare/blob/master/Analise%20de%20Partidas%20de%20Futebol%20usando%20Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#pip install pandas

In [ ]:
import pandas as pd

Realizando a leitura dos dados

Podemos abrir diversos tipos de arquivos com a biblioteca pandas:

pd.read_csv()
pd.read_excel()
pd.read_json()
pd.read_html()

In [ ]:
dados = pd.read_csv('/content/sample_data/campeonato-brasileiro-full.csv', sep =  ",")

In [ ]:
dados.head(10)

,ID,rodata,data,hora,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,vencedor,arena,mandante_Placar,visitante_Placar,mandante_Estado,visitante_Estado
0,1,1,29/03/2003,16:00,Guarani,Vasco,NaN,NaN,NaN,NaN,Guarani,Brinco de Ouro,4,2,SP,RJ
1,2,1,29/03/2003,16:00,Athletico-PR,Gremio,NaN,NaN,NaN,NaN,Athletico-PR,Arena da Baixada,2,0,PR,RS
2,3,1,30/03/2003,16:00,Flamengo,Coritiba,NaN,NaN,NaN,NaN,-,Maracanã,1,1,RJ,PR
3,4,1,30/03/2003,16:00,Goias,Paysandu,NaN,NaN,NaN,NaN,-,Serra Dourada,2,2,GO,PA
4,5,1,30/03/2003,16:00,Internacional,Ponte Preta,NaN,NaN,NaN,NaN,-,Beira Rio,1,1,RS,SP
5,6,1,30/03/2003,16:00,Criciuma,Fluminense,NaN,NaN,NaN,NaN,Criciuma,Heriberto Hulse,2,0,SC,RJ
6,7,1,30/03/2003,16:00,Juventude,Sao Paulo,NaN,NaN,NaN,NaN,-,Alfredo Jaconi,2,2,RS,SP
7,8,1,30/03/2003,16:00,Fortaleza,Bahia,NaN,NaN,NaN,NaN,-,Castelão,0,0,CE,BA
8,9,1,30/03/2003,16:00,Cruzeiro,Sao Caetano,NaN,NaN,NaN,NaN,-,Mineirão,2,2,MG,SP
9,10,1,30/03/2003,16:00,Vitoria,Figueirense,NaN,NaN,NaN,NaN,-,Barradão,1,1,BA,SC

In [ ]:
dados.shape

(8405, 16)

In [ ]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8405 entries, 0 to 8404
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  8405 non-null   int64
 1   rodata              8405 non-null   int64
 2   data                8405 non-null   object
 3   hora                8405 non-null   object
 4   mandante            8405 non-null   object
 5   visitante           8405 non-null   object
 6   formacao_mandante   3431 non-null   object
 7   formacao_visitante  3431 non-null   object
 8   tecnico_mandante    3795 non-null   object
 9   tecnico_visitante   3795 non-null   object
 10  vencedor            8405 non-null   object
 11  arena               8405 non-null   object
 12  mandante_Placar     8405 non-null   int64
 13  visitante_Placar    8405 non-null   int64
 14  mandante_Estado     8405 non-null   object
 15  visitante_Estado    8405 non-null   object
dtypes: int64(4), object(12)
memory usage: 1.0+ MB

In [ ]:
colunas = {"", ""}
# dados = dados.drop(columns  = colunas, axis = 1)
dados.columns

Index(['ID', 'rodata', 'data', 'hora', 'mandante', 'visitante',
       'formacao_mandante', 'formacao_visitante', 'tecnico_mandante',
       'tecnico_visitante', 'vencedor', 'arena', 'mandante_Placar',
       'visitante_Placar', 'mandante_Estado', 'visitante_Estado'],
      dtype='object')

In [ ]:
dados.describe(include = "all")

,ID,rodata,data,hora,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,vencedor,arena,mandante_Placar,visitante_Placar,mandante_Estado,visitante_Estado
count,8405.00000,8405.000000,8405,8405,8405,8405,3431,3431,3795,3795,8405,8405,8405.000000,8405.000000,8405,8405
unique,NaN,NaN,1943,186,45,45,21,21,214,215,46,162,NaN,NaN,15,15
top,NaN,NaN,06/07/2008,16:00,Sao Paulo,Flamengo,4-2-3-1,4-2-3-1,L. Venker de Menezes,L. Venker de Menezes,-,Maracanã,NaN,NaN,SP,SP
freq,NaN,NaN,15,1897,409,410,1965,1858,130,131,2221,631,NaN,NaN,2097,2097
mean,4203.00000,20.133254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.541225,1.027008,NaN,NaN
std,2426.45884,11.444643,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.230607,1.027170,NaN,NaN
min,1.00000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN
25%,2102.00000,10.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.000000,NaN,NaN
50%,4203.00000,20.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,NaN,NaN
75%,6304.00000,30.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,2.000000,NaN,NaN
max,8405.00000,46.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.000000,7.000000,NaN,NaN

In [ ]:
#dados[["partida_id", "clube", "rodata", "chutes", "chutes_no_alvo", "faltas", "posse_de_bola"]]

In [ ]:
dados["mandante"] == "Palmeiras"

0       False
1       False
2       False
3       False
4       False
        ...
8400    False
8401    False
8402    False
8403    False
8404    False
Name: mandante, Length: 8405, dtype: bool

In [ ]:
dados.isna()

,ID,rodata,data,hora,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,vencedor,arena,mandante_Placar,visitante_Placar,mandante_Estado,visitante_Estado
0,False,False,False,False,False,False,True,True,True,True,False,False,False,False,False,False
1,False,False,False,False,False,False,True,True,True,True,False,False,False,False,False,False
2,False,False,False,False,False,False,True,True,True,True,False,False,False,False,False,False
3,False,False,False,False,False,False,True,True,True,True,False,False,False,False,False,False
4,False,False,False,False,False,False,True,True,True,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8400,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8401,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8402,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8403,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8404,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
dados.isna().sum()

ID                       0
rodata                   0
data                     0
hora                     0
mandante                 0
visitante                0
formacao_mandante     4974
formacao_visitante    4974
tecnico_mandante      4610
tecnico_visitante     4610
vencedor                 0
arena                    0
mandante_Placar          0
visitante_Placar         0
mandante_Estado          0
visitante_Estado         0
dtype: int64

In [ ]:
""" colunas = []
for coluna in dados.columns:
  if dados[coluna].isna().sum() != 0:
    colunas.append(coluna)
dados[coluna] """

' colunas = []\nfor coluna in dados.columns:\n  if dados[coluna].isna().sum() != 0:\n    colunas.append(coluna)\ndados[coluna] '

In [ ]:
dados.fillna(0, inplace = True)

In [ ]:
 # dados.fillna.sum()

# dados['Tempo em Campo'] == 0

dados.groupby("vencedor").mean("mandante_Placar")

                          ID     rodata  mandante_Placar  visitante_Placar
vencedor
-                4279.613237  19.528591         0.971184          0.971184
America-MG       6685.879310  21.172414         1.689655          0.862069
America-RN       2037.250000  13.500000         1.750000          1.750000
Athletico-PR     4309.475728  21.126214         1.812298          0.990291
Atletico-GO      5655.194444  21.027778         1.666667          1.166667
Atletico-MG      4740.189602  20.122324         1.831804          1.113150
Avai             4730.212121  19.727273         1.712121          1.045455
Bahia            5381.732283  20.322835         1.637795          0.992126
Barueri          2884.083333  18.166667         2.666667          1.000000
Botafogo-RJ      4385.040486  19.044534         1.700405          1.048583
Bragantino       7677.581818  19.800000         1.690909          1.036364
Brasiliense      1307.700000  19.000000         1.700000          1.300000
CSA              6714.875000  21.250000         1.250000          0.500000
Ceara            6040.666667  18.777778         1.569444          0.930556
Chapecoense      5723.442857  20.657143         1.557143          0.900000
Corinthians      4349.506135  19.638037         1.582822          1.024540
Coritiba         3835.544974  21.000000         1.767196          0.862434
Criciuma         2095.960000  19.280000         1.800000          0.800000
Cruzeiro         3507.644737  20.345395         1.750000          1.197368
Cuiaba           7892.558824  20.588235         1.176471          0.970588
Figueirense      2609.154930  22.063380         1.718310          1.084507
Flamengo         4670.048023  20.621469         1.694915          1.081921
Fluminense       4411.791925  20.083851         1.673913          1.130435
Fortaleza        5355.953704  21.250000         1.805556          1.027778
Goias            3452.674641  21.248804         1.842105          1.124402
Gremio           4478.275316  20.098101         1.734177          0.990506
Gremio Prudente  3256.428571  17.571429         2.571429          1.142857
Guarani          1104.138889  21.722222         1.805556          0.833333
Internacional    4168.613569  20.227139         1.663717          1.000000
Ipatinga         2536.111111  21.444444         2.333333          0.555556
Joinville        5174.142857  19.285714         1.857143          0.714286
Juventude        2258.870588  21.658824         1.611765          0.894118
Nautico          3071.870370  20.685185         2.000000          0.944444
Palmeiras        4785.519757  19.686930         1.772036          1.173252
Parana           1451.542169  21.445783         1.903614          1.132530
Paysandu          792.975610  24.463415         2.390244          0.926829
Ponte Preta      3084.543860  18.535088         1.701754          0.903509
Portuguesa       3742.354839  19.548387         2.096774          0.870968
Santa Cruz       3770.333333  18.133333         2.133333          0.933333
Santo Andre      2914.090909  21.363636         1.909091          1.181818
Santos           4087.188235  20.579412         1.900000          1.082353
Sao Caetano       911.276923  22.984615         1.600000          0.938462
Sao Paulo        4047.646575  20.534247         1.723288          1.104110
Sport            4853.717557  19.770992         1.717557          0.877863
Vasco            3810.105769  20.192308         1.673077          1.024038
Vitoria          3460.699187  19.300813         2.000000          1.227642

In [ ]:
dados["mandante_Estado"] == "RJ"

0       False
1       False
2        True
3       False
4       False
        ...
8400    False
8401    False
8402    False
8403    False
8404     True
Name: mandante_Estado, Length: 8405, dtype: bool

In [ ]:
dados.groupby('mandante').median('mandante_Placar')#.round(2)

                     ID  rodata  mandante_Placar  visitante_Placar
mandante
America-MG       6886.0    19.0              1.0               1.0
America-RN       2118.0    19.0              0.0               1.0
Athletico-PR     4508.5    20.0              1.0               1.0
Atletico-GO      5921.0    20.0              1.0               1.0
Atletico-MG      4510.0    20.0              2.0               1.0
Avai             5171.0    19.0              1.0               1.0
Bahia            5910.0    20.0              1.0               1.0
Barueri          2900.0    20.0              2.0               1.0
Botafogo-RJ      4154.0    20.0              1.0               1.0
Bragantino       7652.5    19.5              1.0               1.0
Brasiliense      1349.0    23.0              1.0               2.0
CSA              6685.0    18.0              1.0               1.0
Ceara            6689.0    19.0              1.0               1.0
Chapecoense      5931.0    19.0              1.0               1.0
Corinthians      4505.0    20.0              1.0               1.0
Coritiba         4314.0    21.0              1.0               1.0
Criciuma         1016.0    21.0              1.0               1.0
Cruzeiro         3749.0    20.0              2.0               1.0
Cuiaba           7842.0    20.0              1.0               1.0
Figueirense      2410.0    21.0              1.0               1.0
Flamengo         4335.0    20.0              1.0               1.0
Fluminense       4305.0    20.0              1.0               1.0
Fortaleza        6833.0    20.0              1.0               1.0
Goias            3193.0    20.0              1.0               1.0
Gremio           4330.0    20.0              2.0               1.0
Gremio Prudente  3286.0    20.0              1.0               1.0
Guarani           792.0    22.0              1.0               1.0
Internacional    4119.0    20.0              1.0               1.0
Ipatinga         2514.0    19.0              1.0               1.0
Joinville        5182.0    20.0              1.0               1.0
Juventude        1649.0    20.0              1.0               1.0
Nautico          2905.0    20.0              1.0               1.0
Palmeiras        4740.0    20.0              2.0               1.0
Parana           1457.5    21.0              1.0               1.0
Paysandu          797.0    23.0              2.0               1.0
Ponte Preta      3929.0    21.0              1.0               1.0
Portuguesa       4039.0    20.0              1.0               1.0
Santa Cruz       3653.0    20.0              1.0               1.0
Santo Andre      2888.0    19.0              1.0               1.0
Santos           4300.0    20.0              2.0               1.0
Sao Caetano      1027.0    22.5              1.0               1.0
Sao Paulo        4327.0    20.0              2.0               1.0
Sport            5174.0    20.0              1.0               1.0
Vasco            3748.5    20.0              1.0               1.0
Vitoria          3392.5    20.0              1.0               1.0

In [ ]:
soma_dados = dados.groupby("vencedor").max("mandante_Placar")
soma_dados.head()

                ID  rodata  mandante_Placar  visitante_Placar
vencedor
-             8400      46                5                 5
America-MG    8391      38                4                 4
America-RN    2078      29                3                 3
Athletico-PR  8395      44                7                 6
Atletico-GO   7973      38                5                 4

In [ ]:
#soma_dados2 = dados.count(['visitante'] and ['vencedor'] == 'Palmeiras')
#print(soma_dados2)

In [ ]:
#dados[['mandante', 'visitante', 'mandante_Placar', 'visitante_Placar', 'vencedor']].sort_values("vencedor", ascending = False)

In [ ]:
dados[['mandante', 'visitante', 'mandante_Placar', 'visitante_Placar', 'vencedor']].sort_values("vencedor")

           mandante      visitante  mandante_Placar  visitante_Placar vencedor
7069    Atletico-GO    Corinthians                1                 1        -
4206          Vasco       Flamengo                1                 1        -
7533  Internacional    Corinthians                2                 2        -
1908          Vasco      Juventude                1                 1        -
4204     Portuguesa         Gremio                2                 2        -
...             ...            ...              ...               ...      ...
3148        Vitoria   Athletico-PR                1                 0  Vitoria
5421        Vitoria  Internacional                1                 0  Vitoria
3123        Vitoria    Atletico-MG                4                 3  Vitoria
1047        Vitoria         Gremio                2                 0  Vitoria
3232       Cruzeiro        Vitoria                0                 1  Vitoria

[8405 rows x 5 columns]

In [ ]:
dados.to_csv("/content/sample_data/dados_campeonato.csv", index = False)